# Generated by Django 3.1.4 on 2021-01-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsletterrecipient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecipient',
            new_name='NewsLetterRecipients',
        ),
    ]
